{
 "title": "Solar-pvpc",
 "time": { "from": "2021-12-29T11:56:03.937Z", "to": "2021-12-31T15:47:05.475Z" },
 "panels": [
  {
   "title": "Energy Overview",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "graphics",
     "query": "SELECT mean(\"consumtion\") FROM \"graphics\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "consumtion" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Surplus Energy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "graphics",
     "query": "SELECT mean(\"available\") FROM \"graphics\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "available" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Production",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "graphics",
     "query": "SELECT mean(\"production\") FROM \"graphics\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "production" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gateway",
     "select": [
      [
       { "params": [ "bateria" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current production",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gateway",
     "select": [
      [
       { "params": [ "produccion" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current consumption",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "gateway",
     "select": [
      [
       { "params": [ "consumo" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Saved last 24h",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 4 },
   "format": "currencyEUR",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "saved",
     "select": [
      [
       { "params": [ "saved" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pending",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 4 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "graphics",
     "select": [
      [
       { "params": [ "pending" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PVPC (REE)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "€/kW" }
   ],
   "targets": [
    {
     "alias": "pvpc",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pvpc",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clouds (weather)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "clouds",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "clouds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Visibility (weather)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "visibility",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "visibility" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature (weather)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity (weather)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "humidity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}